In [7]:
l = [1,4,3,2,2]

print(int(7/2))

print(l[int(-1/2):int(7/2)])

3
[1, 4, 3]


In [8]:
"""
from pytube import YouTube
yt = YouTube("https://www.youtube.com/watch?v=8Lq_7DHbsPw&t=23s")
video = yt.get('mp4', '360p')
yt.set_filename('Video_1')
video.download('./')
"""
import pytube
link = "https://www.youtube.com/watch?v=ocZqvs7gUzc"
yt = pytube.YouTube(link)
stream = yt.streams.first()
stream.download()

In [12]:
#tf slim import tensorflow.contrib.slim as slim; eval = slim.evaluation.evaluate_once
#!pip install pycocotools
#python object_detection/builders/model_builder_test.py
#!pip install --user -r official/requirements.txt
#!pip install python-ldap
import pycocotools

In [44]:
import numpy as np
import cv2
import time
from sklearn.preprocessing import StandardScaler

v = cv2.VideoCapture("Intern_Video.mp4")
success, image = v.read()


v.set(cv2.CAP_PROP_POS_AVI_RATIO,1)
print(v.get(cv2.CAP_PROP_POS_MSEC))

fps = v.get(cv2.CAP_PROP_FPS)
print(fps)

total = v.get(cv2.CAP_PROP_FPS) * v.get(cv2.CAP_PROP_POS_MSEC) / 1000
print(total)

gap = total / 10
print("sdf")
print(gap)
i = 0
count = 0;
seconds = 5
multiplier = fps * seconds
print(multiplier)
while success:
    frameId = int(round(v.get(1))) #current frame number, rounded b/c sometimes you get frame intervals which aren't integers...this adds a little imprecision but is likely good enough
    success, image = v.read()
    print(frameId)
    if frameId % multiplier == 0:
        cv2.imwrite("image%d.jpg" % i, image)
    i = i+1
    
#################### Setting up the file ################
videoFile = "Intern_Video.mp4"
vidcap = cv2.VideoCapture(videoFile)
success,image = vidcap.read()

#################### Setting up parameters ################

#OpenCV is notorious for not being able to good to 
# predict how many frames are in a video. The point here is just to 
# populate the "desired_frames" list for all the individual frames
# you'd like to capture. 

fps = vidcap.get(cv2.CAP_PROP_FPS)
#est_video_length_minutes = 3         # Round up if not sure.
#est_tot_frames = est_video_length_minutes * 60 * fps  # Sets an upper bound # of frames in video clip

n = 10                             # Desired interval of frames to include
desired_frames = np.arange(0,int(total),int(gap)) 


#################### Initiate Process ################
print(desired_frames)
for i in desired_frames:
    print(i)
    vidcap.set(1,i-1)                      
    success,image = vidcap.read(1)         # image is an array of array of [R,G,B] values
    frameId = vidcap.get(1)                # The 0th frame is often a throw-away
    cv2.imwrite("image%d.jpg" % i, image)

vidcap.release()
print ("Complete")    



279249.4666666667
14.979437740495834
4183.000000000001
sdf
418.30000000000007
74.89718870247917
4183
4184
[   0  418  836 1254 1672 2090 2508 2926 3344 3762 4180]
0
418
836
1254
1672
2090
2508
2926
3344
3762
4180
Complete


In [27]:
import numpy as np
import cv2
import time
from sklearn.preprocessing import StandardScaler

fast = cv2.FastFeatureDetector_create()
scaler = StandardScaler()

count = 0
vidcap = cv2.VideoCapture("Intern_Video.mp4")
success,image = vidcap.read()
#print(image)
#cv2.imwrite("frame%d.jpg" % count, image)
main_sol = []
count = 0
while success:
  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
  success,image = vidcap.read() 
  sol = []
  print(image.mean(axis=0).mean(axis=0))
  for ele in image:
    scaled = scaler.fit_transform(ele)
    sol.append(scaled.mean(axis=0))
  #print('Read a new frame: ', success)
  scaled_sol = scaler.fit_transform(sol)
  main_sol.append(scaled_sol.mean(axis=0))  
  count += 1
  if count > 30:
    break
 
ans = scaler.fit_transform(main_sol)
#print(ans.mean(axis=0))

[ 133.05434787  136.93767144  139.02779405]


C:\Users\prate\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


[ 133.20868056  137.01879449  139.20604601]
[ 132.86098307  136.84848741  138.86601997]
[ 132.87698676  136.81509657  138.93180556]
[ 132.82439128  136.75031901  138.8651964 ]
[ 132.77454102  136.60522786  138.6283724 ]
[ 132.66552843  136.47861328  138.49088325]
[ 132.5274056   136.31454861  138.20538737]
[ 132.64895074  136.23031033  138.22827691]
[ 132.71746528  136.41427734  138.3020714 ]
[ 132.95937609  136.67844076  138.66754123]
[ 133.31551432  137.00043294  138.87105469]
[ 133.59244792  137.31074653  139.20503472]
[ 133.8411339   137.60809028  139.45625326]
[ 134.02243056  137.65049045  139.52358832]
[ 134.11340603  137.80182292  139.63802951]
[ 134.23789931  137.88971788  139.69102865]
[ 134.23195312  137.90082682  139.66790256]
[ 134.45089518  138.0008941   139.73615451]
[ 134.38276801  137.85866319  139.5760753 ]
[ 134.13623481  137.50184896  139.19287435]
[ 133.95143229  137.45867296  139.24395508]
[ 133.7209592   137.21815213  139.01417643]
[ 133.06037001  136.6363444   13

In [2]:
import numpy as np
import cv2
import time
from sklearn.preprocessing import StandardScaler

cap = cv2.VideoCapture('small.mp4')
#time.sleep(12)

fgbg = cv2.createBackgroundSubtractorMOG2(detectShadows = False)

sol = []

while(1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)
    #print(fgmask)
    #print("sad")
    if fgmask is not None:
        cv2.imshow('frame',fgmask)
    else:
        break
    scaler = StandardScaler()
    scaled = scaler.fit_transform(fgmask)
    sol.append(scaled.mean(axis=0))
    k = cv2.waitKey(30) & 0xff
    if k == 24:
        break
        
solut = scaler.fit_transform(sol)
ans = solut.mean(axis=0)
print(ans)
print(len(ans))

#print()
cap.release()
cv2.destroyAllWindows()

C:\Users\prate\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


[  1.76626390e-17   9.54623586e-17  -4.92030659e-17 ...,   4.20539024e-17
  -1.09865820e-17   7.69586415e-17]
1280


In [2]:
#!pip install sklearn
import subprocess
import sys
import moviepy.editor as mp
from sklearn.preprocessing import StandardScaler

#subprocess.check_call(["python", '-m', 'pip', 'install', 'python_speech_features']) 

from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav

clip = mp.VideoFileClip("D:\Internship Course\Intern_Video.mp4").subclip(0,20)
clip.audio.write_audiofile("D:\Internship Course/theaudio.wav")
#aud = clip.audio

#(rate,sig) = wav.read("D:\Internship Course\Intern_Video (audio-extractor.net).wav")
(rate,sig) = wav.read("D:\Internship Course/theaudio.wav")
#(rate,sig) = wav.read(aud)

mfcc_feat = mfcc(sig,rate)
print(mfcc_feat)
print(mfcc_feat.mean(axis=0))

scaler = StandardScaler()
mfcc_brahms_scaled = scaler.fit_transform(mfcc_feat)

#print(mfcc_brahms_scaled.mean(axis=0))
#print(mfcc_brahms_scaled.std(axis=0))

clip = mp.VideoFileClip("D:\Internship Course\Intern_Video.mp4").subclip(20,30)
clip.audio.write_audiofile("D:\Internship Course/theaudio2.wav")
(rate,sig) = wav.read("D:\Internship Course/theaudio2.wav")
#(rate,sig) = wav.read(aud)

mfcc_feat = mfcc(sig,rate)

#print(mfcc_feat)

scaler = StandardScaler()
mfcc_brahms_scaled = scaler.fit_transform(mfcc_feat)

print(mfcc_brahms_scaled.mean(axis=0))
print(mfcc_brahms_scaled.std(axis=0))



[MoviePy] Writing audio in D:\Internship Course/theaudio.wav


100%|██████████████████████████████████████████████████████████████████████████████| 442/442 [00:00<00:00, 1064.33it/s]


[MoviePy] Done.


[[ 12.15521365   0.0893386   -5.74882615 ..., -19.94189035  29.39900135
   -4.02063692]
 [ 13.77454063  -8.36823993 -20.85569866 ..., -33.63722288   7.19106444
  -16.8422176 ]
 [ 14.55815569  -5.97695509 -17.03893856 ..., -20.54005049  17.23113983
   -9.36166419]
 ..., 
 [ 15.71398585   3.2666522   -7.53687257 ..., -13.05792732  11.39283337
  -17.1522641 ]
 [ 15.72649352   3.04601725  -4.63363453 ...,  -6.85649956  19.20713153
  -16.63968864]
 [ 15.60213665   7.56590088  -0.10090777 ...,  -6.22517086  14.85190329
  -15.43818841]]
[ 16.90266464   7.79739865  -5.64484033   5.71622376  14.3482817
 -24.27459906  13.35150636 -11.82389775  -0.52348159  11.97996473
 -14.29369929  11.35537696 -10.90167142]
[MoviePy] Writing audio in D:\Internship Course/theaudio2.wav


100%|███████████████████████████████████████████████████████████████████████████████| 221/221 [00:00<00:00, 365.80it/s]


[MoviePy] Done.


[ -5.19599926e-15  -7.59550279e-16   6.17870493e-17   1.92164666e-17
  -2.26834837e-16   1.16964967e-16   2.38081468e-16  -4.84646507e-17
  -1.34796432e-16  -1.17037168e-15  -1.53834479e-15   8.34194589e-17
   7.65048633e-16]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [4]:
import numpy as np
import cv2
import time

cap = cv2.VideoCapture('small.mp4')
#time.sleep(12)

fgbg = cv2.createBackgroundSubtractorMOG2(detectShadows = False)

while(1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)
    print(fgmask)
    print("sad")
    if fgmask is not None:
        cv2.imshow('frame',fgmask)
    else:
        break
    k = cv2.waitKey(30) & 0xff
    if k == 24:
        break

#print()
cap.release()
cv2.destroyAllWindows()

[[255 255 255 ..., 255 255 255]
 [255 255 255 ..., 255 255 255]
 [255 255 255 ..., 255 255 255]
 ..., 
 [255 255 255 ..., 255 255 255]
 [255 255 255 ..., 255 255 255]
 [255 255 255 ..., 255 255 255]]
sad
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
sad
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
sad
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
sad
[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]]
sad
[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   

[[  0 255   0 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ..., 255   0   0]
 [  0   0   0 ..., 255   0   0]]
sad
[[  0   0 255 ...,   0   0   0]
 [  0 255 255 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0 255   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ..., 255   0   0]]
sad
[[  0   0 255 ...,   0   0   0]
 [255   0 255 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ..., 255 255   0]
 [  0   0   0 ..., 255   0   0]
 [  0   0   0 ..., 255   0   0]]
sad
[[  0   0   0 ...,   0   0   0]
 [  0   0 255 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0 255   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0 255   0]]
sad
[[  0   0   0 ...,   0   0   0]
 [  0 255   0 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0 255   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...

 [  0   0   0 ...,   0 255 255]]
sad
[[255 255 255 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 [255 255 255 ...,   0   0   0]
 ..., 
 [  0   0   0 ..., 255 255   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0 255 255]]
sad
[[255 255 255 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ..., 255 255 255]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0 255 255]]
sad
[[255 255   0 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 [255 255   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ..., 255 255 255]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0 255 255]]
sad
[[255   0   0 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0 255 255]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0 255]]
sad
[[255   0   0 ...,   0   0   0]
 [255   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0 255]
 [  0   0   

[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0 255]]
sad
[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0 255]]
sad
None
sad


In [6]:
#!pip install nibabel
#!pip install duecredit
#!pip install bids

#!pip install python-magic-bin==0.4.14

from pliers.filters import FrameSamplingFilter
from pliers.extractors import ClarifaiAPIExtractor, merge_results
import moviepy.editor as mp
from os.path import join
from bids.tests import get_test_data_path
import magic

#video = join("","Intern_Video.mp4")

#print(video)

#clip = mp.VideoFileClip("D:\Internship Course\Intern_Video.mp4").subclip(0,20)

sampler = FrameSamplingFilter(every=10)
frames = sampler.transform("small.mp4")



FileNotFoundError: [WinError 2] The system cannot find the file specified

In [1]:
import subprocess
import sys
import moviepy.editor as mp

#subprocess.check_call(["python", '-m', 'pip', 'install', 'python_speech_features']) 

from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav

clip = mp.VideoFileClip("D:\Internship Course\Intern_Video.mp4").subclip(0,20)
clip.audio.write_audiofile("D:\Internship Course/theaudio.wav")
#aud = clip.audio

#(rate,sig) = wav.read("D:\Internship Course\Intern_Video (audio-extractor.net).wav")
(rate,sig) = wav.read("D:\Internship Course/theaudio.wav")
#(rate,sig) = wav.read(aud)

mfcc_feat = mfcc(sig,rate)

print(mfcc_feat)

#y, sr = librosa.load(librosa.util.example_audio_file(), offset=30, duration=5)

[MoviePy] Writing audio in D:\Internship Course/theaudio.wav


100%|███████████████████████████████████████████████████████████████████████████████| 442/442 [00:00<00:00, 982.57it/s]


[MoviePy] Done.


[[ 12.15521365   0.0893386   -5.74882615 ..., -19.94189035  29.39900135
   -4.02063692]
 [ 13.77454063  -8.36823993 -20.85569866 ..., -33.63722288   7.19106444
  -16.8422176 ]
 [ 14.55815569  -5.97695509 -17.03893856 ..., -20.54005049  17.23113983
   -9.36166419]
 ..., 
 [ 15.71398585   3.2666522   -7.53687257 ..., -13.05792732  11.39283337
  -17.1522641 ]
 [ 15.72649352   3.04601725  -4.63363453 ...,  -6.85649956  19.20713153
  -16.63968864]
 [ 15.60213665   7.56590088  -0.10090777 ...,  -6.22517086  14.85190329
  -15.43818841]]


In [5]:
#!pip install opencv-python

"""
import pip

pip.main(['install', 'cv2'])

import cv2
"""

import cv2
count = 0
vidcap = cv2.VideoCapture("Intern_Video.mp4")
success,image = vidcap.read()
print(image)
cv2.imwrite("frame%d.jpg" % count, image)
"""
count = 0
while success:
  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
  success,image = vidcap.read()
  print('Read a new frame: ', success)
  count += 1
 """   

[[[112 129 130]
  [120 137 138]
  [129 144 146]
  ..., 
  [153 157 149]
  [155 158 147]
  [160 163 152]]

 [[117 134 135]
  [124 141 142]
  [132 147 149]
  ..., 
  [153 157 149]
  [158 161 150]
  [163 166 155]]

 [[116 131 133]
  [121 136 138]
  [126 141 143]
  ..., 
  [150 161 152]
  [154 163 154]
  [157 166 157]]

 ..., 
 [[125 120 128]
  [134 129 137]
  [139 136 143]
  ..., 
  [141 151 150]
  [139 149 148]
  [138 148 147]]

 [[120 117 125]
  [131 128 136]
  [140 137 145]
  ..., 
  [140 152 152]
  [138 150 150]
  [137 149 149]]

 [[123 120 128]
  [135 132 140]
  [144 141 149]
  ..., 
  [141 153 153]
  [141 153 153]
  [141 153 153]]]


'\ncount = 0\nwhile success:\n  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      \n  success,image = vidcap.read()\n  print(\'Read a new frame: \', success)\n  count += 1\n '

In [4]:
"""
import pip

#pip.main(['install','--upgrade','pip'])

pip.main(['install', 'python_speech_features'])

#from python_speech_features import mfcc
#from python_speech_features import logfbank
#import scipy.io.wavfile as wav

#(rate,sig) = wav.read("file.wav")
#mfcc_feat = mfcc(sig,rate)
#fbank_feat = logfbank(sig,rate)

#print(fbank_feat[1:3,:])

from converter import Converter
import os
c = Converter()
clip = 'D:\Internship Course\Intern_Video.mp4'
conv = c.convert(clip, 'audio.mp3', {'format':'mp3','audio':{'codec': 'mp3','bitrate':'22050','channels':1}})
for timecode in conv:
    pass    
os.system("mpg123 -w audio.wav audio.mp3")

"""

AttributeError: module 'pip' has no attribute 'main'